apiVersion: v1
kind: Service
metadata:
  name: jupyterhub-hub
spec:
  type: {{ .Values.hub.service.type }}
  {{ if .Values.hub.service.loadBalancerIP -}}
  loadBalancerIP: {{ .Values.hub.service.loadBalancerIP }}
  {{- end }}
  selector:
    name: jupyterhub-hub
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
