apiVersion: v1
kind: Service
metadata:
  name: jupyterhub-proxy-api
spec:
  selector:
    name: jupyterhub-proxy
    component: jupyterhub-proxy
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: jupyterhub-proxy-http
  # toYaml + indent seem a lot more unstable & error prone
  annotations: {{ toJson .Values.proxy.service.annotations }}
  labels: {{ toJson .Values.proxy.service.labels }}
spec:
  type: ClusterIP
  selector:
    name: jupyterhub-proxy
    component: jupyterhub-proxy
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: proxy
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  {{ if .Values.proxy.service.labels -}}
{{ toYaml .Values.proxy.service.labels | indent 4 }}
  {{- end }}
  {{ if .Values.proxy.service.annotations -}}
  annotations:
{{ toYaml .Values.proxy.service.annotations | indent 4 }}
  {{- end }}
  name: jupyterhub-proxy-public
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    name: jupyterhub-proxy
    component: jupyterhub-proxy
    release: {{ .Release.Name }}
  type: ClusterIP

